[Variables]
Main_FG =FFFFFF
Secondary_FG =FF6EF3
Main_BG =313237
Sidebar_And_Player_BG =161825
Cover_Overlay_And_Shadow =C26EFF
Indicator_FG_And_Button_BG =FF00F7
Pressing_FG = cdcdcd
Slider_BG =FF00F7
Sidebar_Indicator_And_Hover_Button_BG =FF6EF3
Scrollbar_FG_And_Selected_Row_BG =A200FF
Pressing_Button_FG = cccccc
Pressing_Button_BG =FF0000
Selected_Button =FFFFFF
Miscellaneous_BG =FF00EE
Miscellaneous_Hover_BG =FF0004
Preserve_1 =FFFFFF
